### ISSUE TITLE
Huge lag on server startup

### ISSUE THREAD

**Issue by DBotThePony** [bdew-minecraft/bdlib#45]
Sampler says "Server has been stalled for 480000 ms."

Stall Report:

```
"Server thread" #28 prio=5
RUNNABLE
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:60)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:37)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
	at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
	at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
	at scala.collection.TraversableLike$class.$plus$plus(TraversableLike.scala:158)
	at scala.collection.AbstractTraversable.$plus$plus(Traversable.scala:104)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:63)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:179)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:165)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
	at scala.collection.TraversableOnce$$anonfun$toMap$1.apply(TraversableOnce.scala:303)
	at scala.collection.TraversableOnce$$anonfun$toMap$1.apply(TraversableOnce.scala:302)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:302)
	at scala.collection.mutable.ArrayOps$ofRef.toMap(ArrayOps.scala:186)
	at net.bdew.lib.rich.RichBlockPos$.neighbours$extension(RichBlockPos.scala:18)
	at net.bdew.lib.multiblock.Tools$.getConnectedNeighbours(Tools.scala:36)
	at net.bdew.lib.multiblock.Tools$.findReachableModules(Tools.scala:49)
	at net.bdew.lib.multiblock.tile.TileController$class.validateModules(TileController.scala:73)
	at net.bdew.lib.multiblock.tile.TileControllerGui.validateModules(TileControllerGui.scala:14)
	at net.bdew.lib.multiblock.tile.TileController$$anonfun$1.apply$mcV$sp(TileController.scala:89)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
	at net.bdew.lib.multiblock.tile.TileControllerGui.func_73660_a(TileControllerGui.scala:14)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
``

**Comment by LemADEC** [comment]
What version? what other mods are involved?

**Comment by DBotThePony** [comment]
This happens when a huge multiblock structure updates (>700 blocks)

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
